In [1]:
import pandas as pd
import numpy as np

In [2]:
my_first_array = np.array([1,3,7,9])

In [3]:
my_first_array

array([1, 3, 7, 9])

In [6]:
my_first_array.sum()


20

In [7]:
my_first_array.max()

9

In [8]:
my_first_array.min()

1

In [9]:
my_first_array.std()

3.1622776601683795

In [10]:
my_first_array.mean()

5.0

In [11]:
first_random_gen = np.random.random(5)

In [12]:
first_random_gen

array([0.45171695, 0.52755656, 0.89462858, 0.2514045 , 0.41195682])

In [15]:
npOns = np.ones(5)

In [16]:
npOns


array([1., 1., 1., 1., 1.])

In [17]:
my_second_array = np.array([1,2,7,5])


In [18]:
print(my_first_array + my_second_array)

[ 2  5 14 14]


In [19]:
print(my_first_array - my_second_array)

[0 1 0 4]


In [20]:
print(my_first_array / my_second_array)

[1.  1.5 1.  1.8]


In [21]:
print(my_first_array * my_second_array)

[ 1  6 49 45]


In [22]:
print(my_first_array[0:3])

[1 3 7]


In [23]:
print(my_first_array[0:3] + my_second_array[0:3])

[ 2  5 14]


In [24]:
print(my_first_array[1:])


[3 7 9]


In [26]:
my_first_matrix = np.array([[1,2,3],[4,5,6]])

In [27]:
print(my_first_matrix)

[[1 2 3]
 [4 5 6]]


In [28]:
print(np.ones([3,7]))

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [29]:
RandomMatrix = np.random.random((7,2))


In [30]:
print(RandomMatrix)

[[0.21655725 0.49997943]
 [0.06114066 0.01688676]
 [0.68799947 0.91707042]
 [0.77856089 0.16293266]
 [0.62768386 0.94416428]
 [0.54253544 0.04437076]
 [0.07388101 0.15649368]]


In [32]:
# to access matrix value

print(RandomMatrix[1,1])

0.016886762889506524


# Aggregating Matrix Values Across Columns and Rows


In [33]:
my_first_matrix.max(axis = 0) #for columns

array([4, 5, 6])

In [34]:
my_first_matrix.max(axis = 1) #for rows

array([3, 6])

#Manipulating Matrices
* Transposing - rows to columns and columns to rows

In [35]:
print(my_first_matrix)

[[1 2 3]
 [4 5 6]]


In [36]:
print(my_first_matrix.T)

[[1 4]
 [2 5]
 [3 6]]


* Reshaping 

In [37]:
print(my_first_matrix)

[[1 2 3]
 [4 5 6]]


In [38]:
print(my_first_matrix.reshape(1,6))

[[1 2 3 4 5 6]]


In [39]:
print(my_first_matrix.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [41]:
print(my_first_matrix.reshape(1,))

ValueError: cannot reshape array of size 6 into shape (1,)